name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        
    - name: Run linting with flake8
      run: |
        echo "Running flake8 linting on app/ folder..."
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Install test dependencies if tests exist
      run: |
        if [ -d "tests" ]; then
          echo "Tests directory found, installing test dependencies..."
          pip install pytest pytest-cov
        else
          echo "No tests directory found, skipping test dependencies."
        fi
        
    - name: Run unit tests
      run: |
        if [ -d "tests" ]; then
          echo "Running unit tests..."
          python -m pytest tests/ -v --tb=short
        else
          echo "No tests directory found, skipping unit tests."
        fi
        
    - name: Check if train.py exists and run training
      run: |
        if [ -f "train.py" ]; then
          echo "Found train.py, running model training..."
          python train.py
        else
          echo "train.py not found, skipping training step."
        fi
        
    - name: Check if eval.py exists and run evaluation
      run: |
        if [ -f "eval.py" ]; then
          echo "Found eval.py, running model evaluation..."
          python eval.py
        else
          echo "eval.py not found, skipping evaluation step."
        fi
        
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ci-results
        path: |
          results/
          model/
          *.log
        retention-days: 30
        
    - name: Summary
      if: always()
      run: |
        echo "## CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Dependencies installed successfully" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Code linting completed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ All checks passed" >> $GITHUB_STEP_SUMMARY